CREATE TABLE Table_aluno
(
	ID_ALUNO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO VARCHAR(1) NOT NULL, -- M(MASCULINO) OU F(FEMININO) -- 
	DATA_CADASTRO DATE NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL,
);
--DEU ERRO NA HORA DE EXECUTAR O COMANDO PORQUE O ID_ALUNO DE TURMAS NÃO É UMA PK--
ALTER TABLE Table_aluno
	ADD CONSTRAINT FK_TURMAS FOREIGN KEY (ID_ALUNO) REFERENCES Turmas (ID_ALUNO);

--Mostra as tabelas que forem especificadas--
/*
select * from Table_aluno;
select * from Situacao;
select * from Cursos;
select * from Turmas;
select * from REGISTRO_PRESENÇA;
*/
--Exclui as tabelas que forem especificadas--
/*
drop table Table_aluno;
drop table Situacao;
drop table Cursos;
drop table Turmas;
drop table REGISTRO_PRESENÇA;
*/
CREATE TABLE Situacao
(
	ID_SITUACAO INT PRIMARY KEY NOT NULL,
	SITUAÇÃO VARCHAR(25) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);

CREATE TABLE Cursos
(
	ID_CURSO INT PRIMARY KEY NOT NULL,
	NOME_CURSO VARCHAR(200) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);

CREATE TABLE Turmas
(
	ID_TURMA INT PRIMARY KEY NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_CURSO INT NOT NULL,
	VALOR_TURMA NUMERIC(15,2) NOT NULL,
	DESCONTO NUMERIC(3,2)NOT NULL,
	DATA_INCIO DATE NOT NULL,
	DATA_TERMINO DATE,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15)
);
ALTER TABLE Turmas
	ADD CONSTRAINT FK_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES Table_aluno (ID_ALUNO);
ALTER TABLE Turmas
	ADD CONSTRAINT FK_CURSO FOREIGN KEY (ID_CURSO) REFERENCES Cursos (ID_CURSO);

CREATE TABLE REGISTRO_PRESENÇA
(
	ID_TURMA INT NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_SITUACAO INT NOT NULL,
	DATA_PRESENCA DATE NOT NULL,
	DATA_CADASTRO DATE NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);
---FK's DE REGISTRO DE PRESENÇA---
ALTER TABLE REGISTRO_PRESENÇA
	ADD CONSTRAINT FK_TURMASRP FOREIGN KEY (ID_TURMA) REFERENCES Turmas (ID_TURMA);
ALTER TABLE REGISTRO_PRESENÇA
	ADD CONSTRAINT FK_ALUNOSRP FOREIGN KEY (ID_ALUNO) REFERENCES Table_aluno (ID_ALUNO);
ALTER TABLE REGISTRO_PRESENÇA
	ADD CONSTRAINT FK_SITUAÇÃORP FOREIGN KEY (ID_SITUACAO) REFERENCES Situacao (ID_SITUACAO);

CREATE TABLE ALUNOS_TURMAS
(
	ID_ALUNO INT NOT NULL,
	ID_TURMA INT NOT NULL, 
	VALOR NUMERIC(13,2) NOT NULL,
	DESCONTO NUMERIC(3,2) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL,
	CONSTRAINT FK_TURMA FOREIGN KEY (ID_TURMA) REFERENCES TURMAS (ID_TURMA),
	CONSTRAINT FK_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES Table_aluno (ID_ALUNO)
);