CREATE TABLE Table_aluno
(
	ID_ALUNO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO VARCHAR(1) NOT NULL, -- M(MASCULINO) OU F(FEMININO) -- 
	DATA_CADASTRO DATE NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL,
);

--Mostra as tabelas que forem especificadas--
/*
select * from Table_aluno;
select * from Situacao;
select * from Cursos;
select * from Turmas;
select * from REGISTRO_PRESENÇA;
*/

--Exclui as tabelas que forem especificadas--
/*
drop table Table_aluno;
drop table Situacao;
drop table Cursos;
drop table Turmas;
drop table REGISTRO_PRESENÇA;
*/

CREATE TABLE Situacao
(
	ID_SITUACAO INT PRIMARY KEY NOT NULL,
	SITUAÇÃO VARCHAR(25) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);

CREATE TABLE Cursos
(
	ID_CURSO INT PRIMARY KEY NOT NULL,
	NOME_CURSO VARCHAR(200) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);

CREATE TABLE Turmas
(
	ID_TURMA INT PRIMARY KEY NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_CURSO INT NOT NULL,
	VALOR_TURMA NUMERIC(15,2) NOT NULL,
	DESCONTO NUMERIC(3,2)NOT NULL,
	DATA_INCIO DATE NOT NULL,
	DATA_TERMINO DATE,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15)
);

CREATE TABLE REGISTRO_PRESENÇA
(
	ID_TURMA INT NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_SITUACAO INT NOT NULL,
	DATA_PRESENCA DATE NOT NULL,
	DATA_CADASTRO DATE NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);